version: "3.1"
services:
  backend:
    container_name: spring-demo-app
    build: spring-demo-app/
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    depends_on:
      - database



  database:
    container_name: demo-db
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - spring-demo-app-data:/var/lib/postgresql/data


  volumes:
    spring-demo-app-data:



